# Generated by Django 5.0.6 on 2024-07-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userProjectsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField()),
                ('spec_id', models.PositiveBigIntegerField()),
                ('grantAccess', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('accessExipration_date', models.DateTimeField(auto_now_add=True)),
                ('ponds_id', models.PositiveBigIntegerField()),
                ('workers_id', models.PositiveBigIntegerField()),
                ('farm_id', models.PositiveBigIntegerField()),
                ('title', models.CharField(max_length=1000)),
            ],
        ),
    ]
