# Generated by Django 5.0.6 on 2024-07-10 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intutiveSpec', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userProjectsList',
            new_name='userProjectsList_catFishFarming',
        ),
    ]
