# Generated by Django 5.0.6 on 2024-07-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intutiveSpec', '0002_rename_userprojectslist_userprojectslist_catfishfarming'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprojectslist_catfishfarming',
            name='summary',
            field=models.CharField(default='Project summarized scope goes here', max_length=2000),
        ),
    ]
